import Head from 'next/head';
import Image from 'next/image';
import { useSettingsContext } from '../contexts/Settings/SettingsContext';
import styles from '../styles/Home.module.css';

export default function Home() {
  const { settings } = useSettingsContext();

  const primaryColor = settings?.theme_colors.find((c) => c.name === 'primary');

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        {settings && settings.logo && (
          <img src={'http://localhost:1337' + settings.logo.url} alt="logo" />
        )}
        <h1>{settings?.title}</h1>
        <p>{settings?.description}</p>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          {settings?.copyright ? (
            <span style={{ color: primaryColor.value }}>
              {settings?.copyright}
            </span>
          ) : (
            <span className={styles.logo}>
              <Image
                src="/vercel.svg"
                alt="Vercel Logo"
                width={72}
                height={16}
              />
            </span>
          )}
        </a>
      </footer>
    </div>
  );
}
